project:
  type: website
  output-dir: ../docs
  render:
    - index.qmd
    - vorbereitung.Rmd
    - einheit-1.Rmd
    - einheit-2.Rmd
    - einheit-3.Rmd
    - einheit-4.Rmd
    - uebungsaufgabe-1.Rmd
    - cheatsheet.md

lang: de

website:
  title: "R-Einführung"
  search: true
  page-navigation: true
  page-footer:
    center: "© 2026 Bella Mironova · TU Wien, SRF · [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.de)"
  sidebar:
    style: docked
    tools:
      - icon: github
        href: https://github.com/bella-mir/r-einfuehrung
    contents:
      - href: index.qmd
        text: Start
      - section: Einheiten
        contents:
          - href: vorbereitung.Rmd
            text: "Vorbereitung"
          - href: einheit-1.Rmd
            text: "1 · Grundlagen"
          - href: einheit-2.Rmd
            text: "2 · Datenstrukturen & Daten einlesen"
          - href: einheit-3.Rmd
            text: "3 · Daten auswerten & visualisieren"
          - href: einheit-4.Rmd
            text: "4 · Bedingungen, Schleifen & Funktionen"
      - href: uebungsaufgabe-1.Rmd
        text: Übungsaufgabe 1
      - href: cheatsheet.md
        text: Cheatsheet

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    code-copy: true
    css: styles.css
